services:
  # Web Service - Main Application
  - type: web
    name: ccl-3-final
    runtime: node
    repo: https://github.com/copp1723/ccl-3_final
    branch: main
    buildCommand: |
      # Install all dependencies including devDependencies for build
      npm install --production=false
      # Build the application
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: ccl-3-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ccl-3-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: ccl-3-db
    plan: starter # or your plan

  # Redis Instance
  - name: ccl-3-redis
    type: redis
    plan: starter # or your plan
    maxmemoryPolicy: allkeys-lru